apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-chart.fullname" . }}-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.auth.rootPassword | b64enc }}
  MYSQL_PASSWORD: {{ .Values.auth.password | b64enc }}
  MYSQL_USER: {{ .Values.auth.username | b64enc }}
  MYSQL_DATABASE: {{ .Values.auth.database | b64enc }}